### PR TITLE
Add `write_cdata_text` method

### PR DESCRIPTION
**Pull request by msrd0**
See #4

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Thanks! I will take a look later.

**Comment by msrd0** [comment]
Did you get a chance to look at this yet?

**Comment by RazrFalcon** [comment]
Sorry, completely forgot about it.

**Comment by msrd0** [comment]
Thanks for merging this. Do you think you could make a 0.1.1 release with this change?

**Comment by RazrFalcon** [comment]
Hopefully this weekends.

**Pull request merged**
