### PR TITLE
Add `write_text_raw` method

### PR DESCRIPTION
**Pull request by msrd0**
This is sometimes necessary, e.g. when inserting JavaScript into an SVG file.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Wouldn't this make XML malformed? Afaik you should use `<![CDATA[ js ]]>` instead.

**Comment by msrd0** [comment]
Yes, I was trying to print `<![CDATA[` but found it would print `&lt;![CDATA[` everytime instead

**Comment by RazrFalcon** [comment]
Then we need `write_cdata`, which is technically a separate node... There is not easy and correct solution.

I think we can add `write_cdata_text` for now. And it must check that text doesn't include `]]>`.

**Comment by msrd0** [comment]
Yes, that sounds like a good idea.

**Pull request closed without merging**
